name: Docker Build & Push

# Запускаем при пуше в main или при pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Настраиваем Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Вход в Docker Hub 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Собираем Docker-образ
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/multiagent-platform:latest
          platforms: linux/amd64,linux/arm64

      # 5. Проверка образа (опционально)
      - name: Inspect Docker image
        run: docker image ls ${{ secrets.DOCKER_USERNAME }}/multiagent-platform:latest
